# Generated by Django 4.2.6 on 2023-11-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alley', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('league_complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.IntegerField(default=1)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.bowler')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.team')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.teammembers')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game_number', models.IntegerField()),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.bowler')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.week')),
            ],
        ),
    ]
