# Generated by Django 4.2.6 on 2023-11-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_bowlerseries_teamseries_remove_teammembers_bowler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseries',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teamseries',
            name='left_team',
        ),
        migrations.RemoveField(
            model_name='teamseries',
            name='right_team',
        ),
        migrations.RemoveField(
            model_name='teamseries',
            name='series_complete',
        ),
        migrations.RemoveField(
            model_name='teamseries',
            name='week',
        ),
        migrations.AddField(
            model_name='teamseries',
            name='lane',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teamseries',
            name='left_or_right',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_complete', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.league')),
                ('left_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_team', to='bowling.team')),
                ('right_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_team', to='bowling.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.week')),
            ],
        ),
        migrations.AddField(
            model_name='teamseries',
            name='head_to_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.headtohead'),
        ),
    ]
