# Generated by Django 4.2.6 on 2023-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_remove_teamseries_league_remove_teamseries_left_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
