# Generated by Django 4.2.6 on 2023-11-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0004_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowler',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bowling.team'),
        ),
    ]
