# Generated by Django 5.0 on 2024-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0005_bowler_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowler',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
