# Generated by Django 5.0.1 on 2024-01-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0006_bowler_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='league_name',
        ),
    ]
